### PR TITLE
Changed resources to resources_bundle

### PR DESCRIPTION
**Pull request by 4taras4**

### CODE REVIEW

**Comment by muukii** [comment]
Thank you for PR
Can I ask you question ?
what's the difference between resources and bundle?

**Comment by 4taras4** [comment]
> Thank you for PR
> Can I ask you question ?
> what's the difference between resources and bundle?

If you use resource or resources in a CocoaPods PodSpec file, you tell Cocoapods that these are the resource files your library will load during runtime.

As resourceBundle cannot change at runtime, it is safe to create it only once (e.g. on app start or when your framework is initialized) and store it into a global variable (or global class property), so you have it always around when needed

**Comment by muukii** [comment]
@4taras4 I see, thank you for explaining!

**Comment by muukii** [comment]
@4taras4 I approved you to run Checks on GitHub Actions.
Can you see the results of the checks?

**Comment by muukii** [comment]
https://github.com/muukii/Brightroom/pull/149

**Pull request closed without merging**
