### PR TITLE
Update SPM swift settings safe

### PR DESCRIPTION
**Pull request by HonQii**
Fix compile error: The package product 'BrightroomEngine' cannot be used as a dependency of this target because it uses unsafe build flags

### CODE REVIEW

**Review by muukii — APPROVED** [review]
Looks nice
is it available from Swift 5.6?

**Comment by HonQii** [comment]
> 

Yes, I am using version 5.6

**Comment by muukii** [comment]
Thanks!

**Comment by alexanderkhitev** [comment]
hey @muukii! Are you planing to release a new version with this update? Thanks.

**Pull request merged**
